from pathlib import Path
from html import escape
import xml.etree.ElementTree as ET
root=Path.home()/'Desktop/DesktopPreset-ChatGPT-Ads-Landing'
g=root/'guides'
base='https://williamleewilliam1-star.github.io/desktoppreset-ads-landing/guides/'
langs={
'en':{'label':'English','light':'How to Import XMP Presets in Lightroom Classic','resolve':'How to Install .CUBE LUTs in DaVinci Resolve','steps':'Step-by-step','note':'Troubleshooting','shop':'Browse DesktopPreset on Etsy'},
'ja':{'label':'日本語','light':'Lightroom ClassicにXMPプリセットを読み込む方法','resolve':'DaVinci Resolveに.CUBE LUTを追加する方法','steps':'操作手順','note':'困ったときは','shop':'DesktopPresetのEtsyショップ'},
'de':{'label':'Deutsch','light':'XMP-Presets in Lightroom Classic importieren','resolve':'CUBE-LUTs in DaVinci Resolve installieren','steps':'Schritt für Schritt','note':'Fehlerbehebung','shop':'DesktopPreset auf Etsy'},
'fr':{'label':'Français','light':'Importer des presets XMP dans Lightroom Classic','resolve':'Installer des LUT .CUBE dans DaVinci Resolve','steps':'Étapes','note':'Dépannage','shop':'DesktopPreset sur Etsy'},
'it':{'label':'Italiano','light':'Importare preset XMP in Lightroom Classic','resolve':'Installare LUT .CUBE in DaVinci Resolve','steps':'Istruzioni','note':'Problemi comuni','shop':'DesktopPreset su Etsy'}
}
data={
'light':{
'en':(['Check your download first. For Lightroom Classic, look for compatible .xmp presets or a ZIP containing the preset files. Do not confuse XMP Develop presets with video .cube LUTs.','Open Lightroom Classic and switch to Develop. Find the Presets panel.','Click the + button in Presets and choose Import Presets.','Select the compatible preset file(s) or a supported .zip archive and confirm Import. Adobe says imported presets are added under User Presets.','Open a representative image, preview the preset and apply it. Review exposure, skin tones and white balance. If available, adjust the Preset Amount slider.'], 'If the preset does not appear, inspect its format, your Lightroom version and whether the preset only supports particular raw files or camera profiles. Adobe documents partially compatible presets.','https://helpx.adobe.com/lightroom-classic/desktop/process-and-develop-photos/apply-presets.html'),
'ja':(['ダウンロードしたファイルを確認します。Lightroom Classicの現像プリセットは通常XMP形式です。動画用の.cube LUTと混同しないでください。','Lightroom Classicを開き、「現像」モジュールの「プリセット」パネルを探します。','プリセットパネルの「＋」を選び、「プリセットを読み込み」を開きます。','対応するXMPファイルまたはZIPファイルを選択して読み込みます。Adobeによると、読み込まれたプリセットはユーザープリセットに追加されます。','写真にプリセットを適用し、露出や肌色、ホワイトバランスを確認します。対応している場合は適用量も調整できます。'],'表示されないときは形式、Lightroomのバージョン、RAW専用設定やカメラプロファイルの互換性を確認してください。','https://helpx.adobe.com/jp/lightroom-classic/desktop/process-and-develop-photos/apply-presets.html'),
'de':(['Zuerst die Dateien prüfen: Für Lightroom Classic benötigst du kompatible XMP-Entwicklungsvorgaben oder ein unterstütztes ZIP-Archiv, keine Video-LUT im .cube-Format.','Lightroom Classic öffnen und zum Modul Entwickeln wechseln. Dort das Bedienfeld Vorgaben suchen.','Im Vorgaben-Bedienfeld auf + klicken und Vorgaben importieren wählen.','Passende XMP-Dateien oder ein ZIP-Archiv auswählen und den Import bestätigen. Adobe ordnet die importierten Vorgaben den Benutzervorgaben zu.','Eine Aufnahme öffnen, die Vorgabe testen und Belichtung, Hauttöne und Weißabgleich kontrollieren. Wenn unterstützt, den Stärkeregler verwenden.'],'Falls die Vorgabe nicht erscheint, Dateiformat, Programmversion sowie RAW- und Kameraprofil-Kompatibilität prüfen.','https://helpx.adobe.com/de/lightroom-classic/desktop/process-and-develop-photos/apply-presets.html'),
'fr':(['Vérifiez le téléchargement : Lightroom Classic utilise des paramètres prédéfinis de développement compatibles, notamment des fichiers XMP ou des archives ZIP prises en charge, et non des LUT vidéo .cube.','Ouvrez Lightroom Classic puis le module Développement et le panneau Paramètres prédéfinis.','Cliquez sur + dans le panneau, puis sur Importer des paramètres prédéfinis.','Sélectionnez les fichiers compatibles ou une archive ZIP et validez. Adobe indique que les presets importés rejoignent le groupe des presets utilisateur.','Appliquez le preset à une photo et vérifiez exposition, peau et balance des blancs. Ajustez l’intensité si le curseur est disponible.'],'Si le preset ne s’affiche pas, vérifiez son format, la version du logiciel et la compatibilité avec le format RAW ou le profil d’appareil photo.','https://helpx.adobe.com/fr/lightroom-classic/desktop/process-and-develop-photos/apply-presets.html'),
'it':(['Controlla il download: Lightroom Classic importa preset di sviluppo compatibili, come file XMP o archivi ZIP supportati. Una LUT video .cube non è un preset XMP.','Apri Lightroom Classic, entra in Sviluppo e individua il pannello Predefiniti.','Premi + nel pannello e scegli Importa predefiniti.','Seleziona i file compatibili oppure un archivio ZIP e conferma. Secondo Adobe, i preset importati sono disponibili tra quelli utente.','Prova un preset su una foto e controlla esposizione, incarnato e bilanciamento del bianco. Se disponibile, regola il cursore dell’intensità.'],'Se il preset non appare, controlla formato, versione di Lightroom e compatibilità con file RAW o profili della fotocamera.','https://helpx.adobe.com/it/lightroom-classic/desktop/process-and-develop-photos/apply-presets.html')
},
'resolve':{
'en':(['Download a .cube LUT and extract it from its ZIP archive. Keep the file in an easy-to-find folder.','Open DaVinci Resolve. Depending on the version, go to Project Settings > Color Management and use Open LUT Folder, or set a custom LUT Location in Preferences.','Copy the .cube file into the LUT folder. Update the LUT list in Project Settings, or refresh the LUT list from the Color page as appropriate for your version.','Open the Color page and find the imported LUT in the LUTs browser. Apply it to a suitable node; use a separate node for exposure/white balance corrections where practical.','Check whether your footage is already Rec.709 or recorded as Log. Do not assume every creative LUT includes Log-to-Rec.709 conversion. Compare the result on scopes and export a short test clip.'],'If the LUT is missing, refresh the LUT list, check the folder path and the file extension. If the image looks extreme, verify color management and whether a technical transform has already been applied.','https://documents.blackmagicdesign.com/UserManuals/DaVinci-Resolve-17-Colorist-Guide.pdf'),
'ja':(['.cube形式のLUTをダウンロードし、ZIPの場合は解凍して保存場所を確認します。','DaVinci Resolveでプロジェクト設定のカラーマネジメントを開き、LUTフォルダーを表示します。バージョンにより環境設定からLUTの保存先を指定する場合もあります。','LUTフォルダーに.cubeをコピーし、LUTリストを更新するか、カラーページでリフレッシュします。','カラーページのLUTブラウザーから該当LUTを選び、適切なノードに適用します。','映像がRec.709かLogかを確認します。クリエイティブLUTがLog変換を兼ねるとは限りません。スコープで確認し、短いテストを書き出します。'],'表示されない場合はフォルダー、拡張子、リスト更新を確認してください。極端な発色なら色管理と二重変換を確認します。','https://documents.blackmagicdesign.com/UserManuals/DaVinci-Resolve-17-Colorist-Guide.pdf'),
'de':(['Die .cube-LUT herunterladen, gegebenenfalls ZIP entpacken und die Datei auffindbar ablegen.','DaVinci Resolve öffnen. Je nach Version unter Projekteinstellungen > Farbmanagement den LUT-Ordner öffnen oder in den Voreinstellungen einen eigenen LUT-Pfad festlegen.','Die .cube-Datei in den LUT-Ordner kopieren und die LUT-Liste aktualisieren beziehungsweise im Farb-Bereich neu laden.','Im Color-Arbeitsbereich die LUT im Browser auswählen und auf einen geeigneten Node anwenden. Belichtungs- und Weißabgleichkorrekturen möglichst getrennt halten.','Prüfen, ob das Material Rec.709 oder Log ist. Kreative LUTs sind nicht automatisch technische Log-Konverter. Ergebnis mit Scopes kontrollieren und einen Test exportieren.'],'Fehlt die LUT, Ordnerpfad, Dateiendung und Aktualisierung prüfen. Bei extremen Farben Farbmanagement und doppelte Transformierung kontrollieren.','https://documents.blackmagicdesign.com/UserManuals/DaVinci-Resolve-17-Colorist-Guide.pdf'),
'fr':(['Téléchargez le fichier .cube et décompressez son archive ZIP si nécessaire.','Dans DaVinci Resolve, ouvrez les paramètres du projet puis Color Management pour accéder au dossier LUT, ou configurez un emplacement de LUT dans les préférences selon la version.','Copiez le fichier .cube dans le dossier et actualisez la liste des LUT, depuis les paramètres ou la page Color selon votre version.','Dans la page Color, recherchez le LUT et appliquez-le sur un nœud adapté. Séparez si possible les corrections d’exposition et de balance des blancs.','Identifiez si la vidéo est en Rec.709 ou Log. Un LUT créatif n’est pas forcément une conversion technique Log vers Rec.709. Contrôlez les scopes puis exportez un court essai.'],'Si le LUT n’apparaît pas, vérifiez dossier, extension et actualisation. Si les couleurs sont excessives, examinez la gestion des couleurs et les doubles conversions.','https://documents.blackmagicdesign.com/UserManuals/DaVinci-Resolve-17-Colorist-Guide.pdf'),
'it':(['Scarica la LUT .cube e, se necessario, estrai il file dall’archivio ZIP.','In DaVinci Resolve apri Impostazioni progetto > Gestione colore e cerca la cartella LUT; in alcune versioni puoi configurare un percorso personalizzato nelle Preferenze.','Copia il file .cube nella cartella e aggiorna l’elenco delle LUT dal pannello corretto per la tua versione.','Nella pagina Colore cerca la LUT e applicala a un nodo appropriato. Quando possibile separa correzioni di esposizione e bilanciamento del bianco.','Verifica se il girato è Rec.709 oppure Log. Una LUT creativa non è necessariamente una conversione tecnica. Controlla gli scopes ed esporta una breve prova.'],'Se la LUT manca, verifica percorso, estensione e aggiornamento dell’elenco. Se i colori sono eccessivi, controlla la gestione colore e possibili trasformazioni duplicate.','https://documents.blackmagicdesign.com/UserManuals/DaVinci-Resolve-17-Colorist-Guide.pdf')
}
}
css='body{background:#f8f7f3;color:#202522;font:17px/1.7 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;margin:0}main{max-width:790px;margin:auto;padding:28px 24px 80px}a{color:#235b55}h1{font-size:clamp(32px,5vw,47px);line-height:1.17}h2{margin-top:36px}nav{display:flex;gap:13px;flex-wrap:wrap}.lang{display:flex;flex-wrap:wrap;gap:12px;margin:20px 0}.lang a[aria-current=page]{font-weight:bold;text-decoration:underline}.steps{padding:0;list-style:none;counter-reset:s}.steps li{counter-increment:s;position:relative;border:1px solid #d9ddd7;background:#fff;border-radius:12px;margin:13px 0;padding:19px 20px 19px 60px}.steps li:before{content:counter(s);position:absolute;left:16px;top:20px;background:#345f53;color:white;border-radius:50%;width:28px;height:28px;text-align:center;line-height:28px}.note{background:#edece7;padding:22px;border-left:3px solid #345f53}.cta{border:1px solid #ddd;background:#fff;border-radius:14px;padding:22px;margin-top:35px}small{color:#555}'
for kind in ('light','resolve'):
 for lang,m in langs.items():
  title=m[kind];steps,notes,source=data[kind][lang];filename=f'{kind}-guide-{lang}.html';url=base+filename
  alts=''.join(f'<link rel="alternate" hreflang="{l}" href="{base}{kind}-guide-{l}.html">' for l in langs)
  switch=' '.join(f'<a href="{kind}-guide-{l}.html"'+(' aria-current="page"' if l==lang else '')+f'>{v["label"]}</a>' for l,v in langs.items())
  cta='https://www.etsy.com/shop/DesktopPreset?utm_source=desktoppreset_guides&amp;utm_medium=organic_content&amp;utm_campaign='+kind+'_guide_'+lang
  intro=('Lightroom Classic development presets are not interchangeable with video LUTs.' if kind=='light' else 'Use a compatible .cube LUT in DaVinci Resolve, and check your project color management before applying creative looks.')
  page=f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | DesktopPreset Guides</title><meta name="description" content="{escape(title,quote=True)}. DesktopPreset step-by-step creator guide."><link rel="canonical" href="{url}">{alts}<style>{css}</style></head><body><main><nav><a href="../">DesktopPreset</a> / <a href="index.html">Guides</a></nav><h1>{escape(title)}</h1><div class="lang">{switch}</div><p>{escape(intro)}</p><h2>{escape(m['steps'])}</h2><ol class="steps">{''.join('<li>'+escape(step)+'</li>' for step in steps)}</ol><h2>{escape(m['note'])}</h2><p>{escape(notes)}</p><aside class="note"><strong>Source:</strong> <a href="{source}" rel="noopener noreferrer">Official {'Adobe Lightroom Classic' if kind=='light' else 'Blackmagic Design DaVinci Resolve'} documentation</a>. Interface labels can change between versions.</aside><section class="cta"><h2>{escape(m['shop'])}</h2><p><a href="{cta}" rel="sponsored noopener noreferrer">DesktopPreset — Etsy →</a></p><small>Disclosure: DesktopPreset publishes this educational guide and sells optional digital products. Product availability and version compatibility should be confirmed on Etsy.</small></section></main></body></html>'''
  (g/filename).write_text(page,encoding='utf8')
idx=g/'index.html';s=idx.read_text();marker='<h2>OBS Studio</h2>';s=s.replace(marker,'<h2>Lightroom Classic</h2><p><a href="light-guide-en.html">How to import XMP Lightroom Classic presets — five languages</a></p><h2>DaVinci Resolve</h2><p><a href="resolve-guide-en.html">How to import .CUBE LUTs — five languages</a></p>'+marker);idx.write_text(s)
sm=root/'sitemap.xml';tree=ET.parse(sm);r=tree.getroot();namespace='{http://www.sitemaps.org/schemas/sitemap/0.9}'
for kind in ('light','resolve'):
 for lang in langs:
  node=ET.SubElement(r,namespace+'url');loc=ET.SubElement(node,namespace+'loc');loc.text=base+f'{kind}-guide-{lang}.html'
ET.indent(tree,space='  ');tree.write(sm,encoding='unicode',xml_declaration=True)
print('New published-ready pages:',10)
