from pathlib import Path
from html import escape
import xml.etree.ElementTree as ET
import json,re
root=Path.home()/'Desktop/DesktopPreset-ChatGPT-Ads-Landing'
g=root/'guides'
base='https://williamleewilliam1-star.github.io/desktoppreset-ads-landing/guides/'
langs=['en','ja','de','fr','it']
common={
'en':('Practical guide','Step-by-step workflow','Before buying a LUT or preset','Common problems','Explore DesktopPreset','Related guides','Creator education. Product compatibility depends on the specific file and software version.'),
'ja':('実用ガイド','操作の流れ','購入前に確認','よくある問題','DesktopPresetの商品','関連ガイド','製品の互換性はファイル形式とアプリのバージョンによって異なります。'),
'de':('Praxisanleitung','Schritt für Schritt','Vor dem Kauf prüfen','Häufige Probleme','DesktopPreset entdecken','Weitere Anleitungen','Die Kompatibilität hängt vom Dateiformat und der Softwareversion ab.'),
'fr':('Guide pratique','Étapes détaillées','Avant d’acheter','Problèmes fréquents','Découvrir DesktopPreset','Guides associés','La compatibilité dépend du format et de la version du logiciel.'),
'it':('Guida pratica','Passaggi','Prima di acquistare','Problemi comuni','Scopri DesktopPreset','Guide correlate','La compatibilità dipende dal formato e dalla versione del software.')
}
content={
'apple-log':{
'en':('Apple Log LUTs: A Reliable iPhone Color Grading Workflow','Apple Log is a recording curve, not a finished cinematic look. Identify your recording settings before adding a LUT.',['Check whether your iPhone video was actually recorded in Apple Log. Standard iPhone footage and Apple Log should not be treated identically.','Import your original video into an editor that supports the recorded format and a predictable color-management workflow.','Apply a correct technical transform for the relevant Apple Log version and target color space when your editor has not already managed the conversion. Avoid converting twice.','After normalization, apply a creative LUT that expects that output color space, then adjust exposure, strength and skin tones.','Export a short reference clip in the intended delivery color space, compare it on your target device, and retain the untreated original.'],'Why does the video look gray? Log footage intentionally uses a flatter encoding. Why is it too contrasty? A conversion may have been applied twice, or the creative LUT expects a different input.','Do not assume that a pack labeled cinematic automatically contains the technical Apple Log transform. Confirm the recording format, color space, .cube compatibility and editor workflow.'),
'ja':('Apple Log LUTの使い方｜iPhone動画の色補正','Apple Logは撮影時の記録方式であり、完成した映画風の色ではありません。',['元のiPhone動画が本当にApple Logで撮影されているか確認します。','対応する動画編集アプリにオリジナル素材を読み込みます。','編集アプリが自動変換していない場合のみ、適切な技術的カラー変換を適用します。二重変換は避けます。','正規化した映像に対応するクリエイティブLUTを適用し、肌色や露出を調整します。','短い動画を書き出して表示機器で確認し、元の素材は必ず保存します。'],'グレーに見えるのはLog特有のフラットな記録のためです。コントラストが強すぎる場合は二重変換や入力色空間の不一致を確認してください。','映画風のLUTが必ずApple Log変換を含むとは限りません。形式と編集アプリの互換性を確認してください。'),
'de':('Apple Log LUTs: iPhone-Videos richtig kolorieren','Apple Log ist ein Aufnahmeprofil, kein fertiger Film-Look.',['Prüfen, ob das iPhone-Video tatsächlich in Apple Log aufgenommen wurde.','Originalmaterial in einen Editor mit passendem Farbmanagement importieren.','Nur wenn noch keine automatische Konvertierung erfolgt ist: eine passende technische Apple-Log-Transformation zum Ziel-Farbraum anwenden. Doppelte Umwandlungen vermeiden.','Danach eine kreative LUT verwenden, die den normalisierten Farbraum erwartet, und Hauttöne sowie Belichtung prüfen.','Kurzen Test exportieren, auf dem Zielgerät vergleichen und die Originaldatei behalten.'],'Graue Log-Bilder sind zunächst normal. Bei übermäßigem Kontrast zuerst nach doppelten Transformationen oder falschem Eingangsfarbraum suchen.','Vor dem Kauf klären, ob eine LUT die technische Apple-Log-Konvertierung oder nur einen kreativen Look liefert.'),
'fr':('LUT Apple Log : étalonner une vidéo iPhone sans erreur','Apple Log est un encodage de prise de vue, pas un rendu cinéma final.',['Vérifiez que la vidéo a réellement été tournée en Apple Log.','Importez le fichier original dans un éditeur avec une gestion des couleurs adaptée.','Si l’éditeur n’a pas déjà converti l’image, appliquez une transformation technique adaptée vers l’espace colorimétrique final. Évitez toute double conversion.','Appliquez ensuite un LUT créatif compatible avec cet espace et contrôlez exposition et teintes de peau.','Exportez un court test, examinez-le sur l’écran cible et conservez l’original.'],'Une image grise est fréquente en Log. Si le contraste est excessif, vérifiez les transformations déjà appliquées et l’espace d’entrée.','Un pack de LUT « cinéma » ne contient pas nécessairement une conversion technique Apple Log. Vérifiez le format et les exigences.'),
'it':('LUT Apple Log: color grading corretto dei video iPhone','Apple Log è un formato di ripresa, non un look cinematografico già pronto.',['Verifica che il video iPhone sia stato registrato davvero in Apple Log.','Importa il file originale in un editor che gestisca correttamente lo spazio colore.','Se non è già stata eseguita una conversione automatica, applica la trasformazione tecnica adatta al formato e alla destinazione. Evita doppie trasformazioni.','Poi applica una LUT creativa compatibile e controlla esposizione, tonalità della pelle e intensità.','Esporta un breve test sul dispositivo di destinazione e conserva il video originale.'],'Un video Log può apparire piatto. Un contrasto eccessivo può indicare una conversione doppia o uno spazio colore di ingresso errato.','Una LUT chiamata cinematic non include necessariamente una conversione tecnica Apple Log. Verifica compatibilità e formato.')
},
'capcut-mac':{
'en':('How to Import .CUBE LUTs in CapCut Desktop on Mac and Windows','CapCut features differ across operating systems, account tiers and app versions. Some Mac users report that the LUT import button is absent. Do not assume a pack will import before verifying your version.',['Open CapCut Desktop and identify its exact version and whether you are using Mac or Windows.','Create a small test project and add a normal video clip to the timeline. Select the clip and inspect Adjustments / Color for any LUT feature or import control.','If an Import or plus button exists, choose a small compatible .cube test LUT. Save the file outside a cloud-only placeholder folder so it is locally accessible.','Apply the imported LUT gently and compare the original and result. Check skin tones, highlights and whether the project is Rec.709 or Log.','If there is no LUT import button, do not force a .cube into the media browser. Check the latest official CapCut documentation and version-specific release notes, or use an editor confirmed to support .cube imports.'],'No plus button? It may be a version/platform limitation, not a broken LUT. A .cube file is a color-lookup table, not a video or image file for ordinary Media import.','Confirm LUT-import support on your actual Mac/Windows build and the required source color space before buying any pack.'),
'ja':('CapCut Desktopで.CUBE LUTを読み込む方法｜Mac・Windows','CapCutのLUT機能はOSやバージョンによって異なり、Mac版で読み込みボタンが表示されないという報告もあります。',['CapCut Desktopの正確なバージョンとMac/Windowsの違いを確認します。','短い動画でテストプロジェクトを作り、タイムラインでクリップを選択します。','調整・カラー関連の画面でLUTや読み込みボタンがあるか確認します。','読み込みが可能なら、小さな.cubeファイルを指定して適用し、元の映像と比較します。','ボタンがなければ通常のメディア読み込みに.cubeを無理に入れず、公式情報とバージョン別の仕様を確認します。'],'＋ボタンがない場合はアプリ側の制限かもしれません。LUTは通常の動画ファイルではありません。','購入前にMac/Windowsの該当バージョンで.cubeの読み込みに対応するか確認してください。'),
'de':('CUBE-LUTs in CapCut Desktop auf Mac und Windows importieren','Die LUT-Importfunktion kann je nach CapCut-Version, Betriebssystem und Tarif unterschiedlich verfügbar sein.',['Die genaue CapCut-Desktop-Version und das Betriebssystem prüfen.','Ein kurzes Testprojekt erstellen, Clip in die Timeline ziehen und auswählen.','Unter Anpassungen/Farbe nach einer LUT- oder Importfunktion suchen.','Falls eine Import-Schaltfläche vorhanden ist, eine kompatible .cube-Datei lokal auswählen und das Ergebnis vorsichtig testen.','Fehlt die Schaltfläche, nicht versuchen, die LUT als gewöhnliches Medienvideo zu importieren. Aktuelle CapCut-Dokumentation und Versionshinweise prüfen.'],'Ein fehlendes Plus-Symbol kann eine Plattform- oder Versionsbeschränkung sein und muss nicht auf eine defekte LUT hinweisen.','Vor dem Kauf die LUT-Importfunktion der konkreten Mac- oder Windows-Version bestätigen.'),
'fr':('Importer une LUT .CUBE dans CapCut Desktop sur Mac ou Windows','L’importation des LUT dans CapCut dépend parfois du système et de la version de l’application.',['Notez la version exacte de CapCut Desktop et le système utilisé.','Créez un projet de test avec un court clip sur la timeline.','Sélectionnez le clip et cherchez les contrôles LUT ou Import dans les réglages de couleur.','Si la fonction est présente, choisissez un petit fichier .cube compatible et comparez le résultat avant/après.','Si aucun bouton n’apparaît, ne chargez pas le .cube comme un média classique ; consultez la documentation officielle pour votre version.'],'L’absence du bouton + peut venir de la version Mac/Windows et ne prouve pas un problème avec votre LUT.','Avant achat, confirmez l’importation de .cube dans la version de CapCut utilisée.'),
'it':('Importare LUT .CUBE in CapCut Desktop su Mac e Windows','Il supporto per importare LUT in CapCut può cambiare tra sistemi operativi e versioni.',['Controlla la versione esatta di CapCut Desktop e se usi Mac o Windows.','Crea un progetto di prova con una breve clip sulla timeline.','Seleziona la clip e cerca le opzioni LUT o Importa nelle regolazioni colore.','Se è presente il pulsante, seleziona un file .cube compatibile e confronta il risultato originale.','Se non vedi il pulsante non forzare il file .cube come media normale. Consulta le informazioni ufficiali relative alla tua versione.'],'Il pulsante + mancante può essere una limitazione della piattaforma e non un errore della LUT.','Prima di acquistare verifica che la tua versione di CapCut importi LUT .cube.')
},
'lightroom-mobile':{
'en':('Lightroom Mobile Presets: How to Import DNG and XMP Correctly','Lightroom mobile import options differ between versions and platforms. DNG-based sample presets and XMP settings are not interchangeable with video LUT files.',['Inspect the pack contents before import. A photo preset might come as XMP files, DNG examples or a supported preset pack; a .cube video LUT is not the same thing.','Update Adobe Lightroom mobile, open a photo and find the Presets panel. Look for the menu to import presets or manage preset groups in your installed version.','If the app supports XMP/ZIP import, choose the compatible files. If you have only DNG example photos, import a DNG image and use its settings as a starting point for creating your own preset, when your version supports it.','Apply the new preset to a test photo. Check exposure, skin tones and whether the source is RAW or JPEG.','If a preset appears missing or partially compatible, confirm app version, cloud sync status and whether the pack requires a camera profile that you do not have.'],'A DNG is a digital negative image, not automatically a ready-made Lightroom preset file. Imported images and preset files may follow different workflows.','Choose a pack specifically labeled for the mobile version and correct import format; desktop Lightroom Classic XMP instructions may not apply to all mobile releases.'),
'ja':('Lightroomモバイルのプリセットを読み込む方法｜DNGとXMPの違い','Lightroomモバイルではアプリのバージョンによって読み込み方法が異なります。',['購入したファイルがXMP、DNG、ZIPのどれなのか確認します。.cube動画用LUTとは異なります。','Lightroomモバイルを更新し、写真を開いてプリセット画面を確認します。','XMPやZIPの読み込みに対応していればプリセットの読み込みメニューから選択します。','DNGのサンプル写真しかない場合は写真を読み込み、対応バージョンなら調整内容からプリセットを作成します。','別の写真に適用して肌色や露出を確認し、表示されない場合は互換性や同期状態を調べます。'],'DNGは画像ファイルで、XMPプリセットそのものではありません。','購入前にモバイル版とファイル形式の対応を確認してください。'),
'de':('Lightroom Mobile Presets importieren: DNG oder XMP?','Der Import unterscheidet sich je nach Lightroom-Mobile-Version und Plattform.',['Dateityp des Pakets prüfen: XMP, DNG, ZIP und Video-LUTs sind nicht dasselbe.','Lightroom Mobile aktualisieren, ein Foto öffnen und das Vorgaben-Bedienfeld suchen.','Wenn XMP/ZIP-Import unterstützt wird, Dateien über die entsprechende Importfunktion auswählen.','Bei DNG-Beispielbildern zunächst das Foto importieren und, falls unterstützt, aus dessen Einstellungen eine eigene Vorgabe erstellen.','An einem Testfoto anwenden; Belichtung, Hauttöne, RAW/JPEG-Unterschiede und eventuelle Sync-Probleme prüfen.'],'DNG ist ein Bildformat und kein universeller Ersatz für XMP-Vorgaben.','Vor dem Kauf das Dateiformat und die Anforderungen der mobilen Version prüfen.'),
'fr':('Presets Lightroom Mobile : importer DNG et XMP','La méthode varie selon la version et la plateforme de Lightroom mobile.',['Vérifiez le type de fichier : XMP, DNG, ZIP et LUT vidéo .cube ne sont pas équivalents.','Mettez Lightroom mobile à jour, ouvrez une photo et trouvez le panneau Paramètres prédéfinis.','Si la version permet d’importer XMP/ZIP, utilisez l’option d’importation correspondante.','Si le pack contient une photo DNG, importez-la et, si votre version le permet, enregistrez ses réglages sous forme de preset.','Appliquez le preset à une photo test et contrôlez les couleurs, l’exposition et la compatibilité RAW/JPEG.'],'Un fichier DNG est une image numérique, pas automatiquement un preset XMP.','Avant achat, vérifiez la version mobile et le format du pack.'),
'it':('Preset Lightroom Mobile: come importare DNG e XMP','Le opzioni di importazione variano tra versioni e sistemi di Lightroom mobile.',['Controlla i file del pacchetto: XMP, DNG, ZIP e LUT video .cube sono diversi.','Aggiorna Lightroom mobile, apri una foto e cerca il pannello Predefiniti.','Se la versione supporta XMP/ZIP, importa i file attraverso l’apposito menu.','Se hai solo immagini DNG, importa la foto e, se la versione lo consente, crea un preset dalle sue regolazioni.','Prova il preset su un’altra foto e controlla esposizione, incarnato e compatibilità con RAW o JPEG.'],'DNG è un formato immagine, non un preset XMP universale.','Prima di comprare verifica compatibilità mobile e formato del pacchetto.')
}}
css='body{margin:0;background:#f8f7f3;color:#212722;font:17px/1.68 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}main{max-width:790px;margin:auto;padding:30px 23px 80px}a{color:#246157}h1{font-size:clamp(32px,5vw,46px);line-height:1.17}h2{margin-top:36px}.lang{display:flex;gap:13px;flex-wrap:wrap;margin:19px 0}.lang a[aria-current=page]{font-weight:700;text-decoration:underline}.steps{padding:0;list-style:none;counter-reset:st}.steps li{position:relative;counter-increment:st;background:white;border:1px solid #dce0da;border-radius:12px;padding:19px 18px 19px 59px;margin:14px 0}.steps li:before{content:counter(st);position:absolute;left:16px;top:20px;display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:#355f54;color:#fff;font-weight:bold}.note{padding:20px;border-left:3px solid #355f54;background:#eee}.cta{margin-top:36px;padding:22px;border:1px solid #ddd;background:#fff;border-radius:14px}small{color:#585e58}'
for topic,variants in content.items():
 for lang,(title,intro,steps,trouble,purchase) in variants.items():
  eyebrow,stepLabel,beforeLabel,troubleLabel,shopLabel,relatedLabel,footer=common[lang]
  fname=f'{topic}-guide-{lang}.html';url=base+fname
  alternate=''.join(f'<link rel="alternate" hreflang="{l}" href="{base}{topic}-guide-{l}.html">' for l in langs)
  languageLinks=' '.join(f'<a href="{topic}-guide-{l}.html" hreflang="{l}"'+(' aria-current="page"' if lang==l else '')+f'>{common[l][0].split()[0] if False else {"en":"English","ja":"日本語","de":"Deutsch","fr":"Français","it":"Italiano"}[l]}</a>' for l in langs)
  etsy='https://www.etsy.com/shop/DesktopPreset?utm_source=desktoppreset_guides&amp;utm_medium=organic_content&amp;utm_campaign='+topic+'_'+lang
  relative='light-guide-en.html' if topic=='lightroom-mobile' else ('resolve-guide-en.html' if topic=='apple-log' else 'sony-slog3-capcut-en.html')
  faq=[{'@type':'Question','name':troubleLabel,'acceptedAnswer':{'@type':'Answer','text':trouble}}]
  structured={'@context':'https://schema.org','@type':'HowTo','name':title,'inLanguage':lang,'url':url,'step':[{'@type':'HowToStep','text':x} for x in steps]}
  jsonld=json.dumps(structured,ensure_ascii=False).replace('</','<\\/')
  page=f'''<!doctype html><html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | DesktopPreset Guides</title><meta name="description" content="{escape(intro[:160],quote=True)}"><link rel="canonical" href="{url}">{alternate}<style>{css}</style><script type="application/ld+json">{jsonld}</script></head><body><main><nav><a href="../">DesktopPreset</a> / <a href="index.html">Guides</a></nav><p>{escape(eyebrow)} · October 2026</p><h1>{escape(title)}</h1><div class="lang">{languageLinks}</div><p>{escape(intro)}</p><h2>{escape(stepLabel)}</h2><ol class="steps">{''.join('<li>'+escape(x)+'</li>' for x in steps)}</ol><h2>{escape(troubleLabel)}</h2><p>{escape(trouble)}</p><aside class="note"><strong>{escape(beforeLabel)}</strong><p>{escape(purchase)}</p></aside><h2>{escape(relatedLabel)}</h2><p><a href="{relative}">{escape(relatedLabel)} →</a></p><section class="cta"><h2>{escape(shopLabel)}</h2><p><a href="{etsy}" rel="sponsored noopener noreferrer">DesktopPreset Etsy ↗</a></p><small>Disclosure: DesktopPreset publishes this independent guide and sells optional digital products on Etsy. This is not an official Apple, Adobe or CapCut support page. {escape(footer)}</small></section></main></body></html>'''
  (g/fname).write_text(page)
idx=g/'index.html';s=idx.read_text()
needle='<h2>OBS Studio</h2>'
add=''.join(f'<h2>{title}</h2><p><a href="{topic}-guide-en.html">{teaser}</a> — English, Japanese, German, French and Italian.</p>' for topic,title,teaser in [('apple-log','Apple Log / iPhone','Color-manage Apple Log footage before creative grading'),('capcut-mac','CapCut Desktop on Mac and Windows','Find LUT import controls and troubleshoot missing buttons'),('lightroom-mobile','Lightroom Mobile','Understand XMP and DNG presets on mobile')])
assert needle in s
s=s.replace(needle,add+needle);idx.write_text(s)
sm=root/'sitemap.xml';tree=ET.parse(sm);r=tree.getroot();ns='{http://www.sitemaps.org/schemas/sitemap/0.9}'
existing=set(el.text for el in r.iter(ns+'loc'))
for topic in content:
 for lang in langs:
  url=base+f'{topic}-guide-{lang}.html'
  if url not in existing:
   n=ET.SubElement(r,ns+'url');ET.SubElement(n,ns+'loc').text=url
ET.indent(tree,space='  ');tree.write(sm,encoding='unicode',xml_declaration=True)
print('Created 15 new guides; sitemap total',len(list(r)))
